from __future__ import annotations

COINS: dict[str, str] = {
      "bitcoin": "BTCUSDT",
    "ethereum": "ETHUSDT",
    "binancecoin": "BNBUSDT",
    "cardano": "ADAUSDT",
    "ripple": "XRPUSDT",
    "polkadot": "DOTUSDT",
    "uniswap": "UNIUSDT",
    "chainlink": "LINKUSDT",
    "litecoin": "LTCUSDT",
    "stellar": "XLMUSDT",
    "usdc": "USDCUSDT",
    "dogecoin": "DOGEUSDT",
    "vechain": "VETUSDT",
    "filecoin": "FILUSDT",
    "tron": "TRXUSDT",
    "eos": "EOSUSDT",
    "aave": "AAVEUSDT",
    "monero": "XMRUSDT",
    "cosmos": "ATOMUSDT",
    "tezos": "XTZUSDT",
    "algorand": "ALGOUSDT",
    "nem": "XEMUSDT",
    "compound": "COMPUSDT",
    "kusama": "KSMUSDT",
    "zilliqa": "ZILUSDT",
    "neo": "NEOUSDT",
    "sushiswap": "SUSHIUSDT",
    "maker": "MKRUSDT",
    "dash": "DASHUSDT",
    "elrond": "EGLDUSDT",
}
